// <auto-generated />
using System;
using DataAccess.Concrete.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20230107234036_PageConfig")]
    partial class PageConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Concrete.AppOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("AppOperationClaims", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "AppUser"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "AppUserType"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppUserTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("GsmNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("GsmNumber");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordSalt");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ProfileImageUrl");

                    b.Property<Guid>("RefreshToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UserName");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.HasKey("Id");

                    b.HasIndex("AppUserTypeId");

                    b.ToTable("AppUsers", "dbo");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedDate = new DateTime(2023, 1, 8, 2, 40, 35, 554, DateTimeKind.Local).AddTicks(6916),
                            CreatedUserId = 1,
                            Email = "sadmin@gmail.com",
                            FirstName = "System",
                            GsmNumber = "",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            PasswordHash = new byte[] { 246, 12, 40, 158, 187, 122, 20, 78, 194, 126, 174, 26, 203, 218, 204, 251, 200, 51, 0, 66, 79, 49, 144, 240, 235, 120, 235, 250, 88, 139, 228, 70, 220, 135, 217, 23, 224, 207, 203, 159, 214, 120, 7, 150, 247, 106, 203, 45, 202, 28, 89, 122, 248, 238, 148, 113, 132, 187, 140, 184, 36, 40, 169, 112 },
                            PasswordSalt = new byte[] { 38, 185, 172, 24, 254, 40, 76, 19, 118, 243, 19, 39, 233, 57, 214, 172, 213, 143, 129, 214, 89, 247, 225, 225, 133, 6, 172, 170, 142, 198, 251, 9, 249, 105, 200, 196, 195, 255, 42, 200, 65, 253, 90, 53, 252, 88, 12, 98, 189, 161, 192, 70, 71, 59, 240, 110, 126, 128, 31, 104, 91, 72, 138, 180, 193, 103, 175, 99, 89, 156, 86, 195, 24, 132, 144, 7, 199, 240, 242, 112, 193, 55, 214, 248, 169, 189, 43, 231, 66, 153, 15, 40, 46, 168, 215, 40, 101, 200, 71, 245, 41, 76, 42, 181, 125, 113, 182, 239, 1, 151, 255, 213, 149, 139, 222, 240, 78, 168, 63, 33, 25, 120, 184, 100, 1, 188, 234, 240 },
                            ProfileImageUrl = "",
                            RefreshToken = new Guid("c9503bd5-40dd-4e99-a475-9c45f8405aea"),
                            UserName = "sadmin",
                            UserTypeID = -1
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UserTypeName");

                    b.HasKey("Id");

                    b.ToTable("AppUserTypes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            UserTypeName = "System Admin"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUserTypeAppOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppOperationClaimId")
                        .HasColumnType("int");

                    b.Property<int?>("AppUserTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OperationClaimID")
                        .HasColumnType("int")
                        .HasColumnName("OperationClaimId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char(4)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.HasKey("Id");

                    b.HasIndex("AppOperationClaimId");

                    b.HasIndex("AppUserTypeId");

                    b.ToTable("AppUserTypeAppOperationClaims", "dbo");
                });

            modelBuilder.Entity("Entities.Concrete.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("MetaDescription");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("MetaKeywords");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("MetaTitle");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PageName");

                    b.Property<string>("PageSeoURL")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PageSeoURL");

                    b.Property<int>("PageTypeID")
                        .HasColumnType("int")
                        .HasColumnName("PageTypeID");

                    b.Property<string>("PageURL")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PageURL");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.HasKey("Id");

                    b.HasIndex("PageTypeID");

                    b.ToTable("Pages", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sistem Ayarları",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "#"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcılar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUsers/List",
                            ParentID = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcılar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUsers/Add",
                            ParentID = 2
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcılar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUsers/Update",
                            ParentID = 2
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcılar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUsers/Delete",
                            ParentID = 2
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcılar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUsers/Detail",
                            ParentID = 2
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserTypes/List",
                            ParentID = 1
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserTypes/Add",
                            ParentID = 7
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserTypes/Update",
                            ParentID = 7
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserTypes/Delete",
                            ParentID = 7
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserTypes/Detail",
                            ParentID = 7
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Pages/List",
                            ParentID = 1
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Pages/Add",
                            ParentID = 12
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Pages/Update",
                            ParentID = 12
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Pages/Delete",
                            ParentID = 12
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Pages/Detail",
                            ParentID = 12
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfa Yetkileri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/PagePermissons/List",
                            ParentID = 1
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "#"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürünler",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Products/List",
                            ParentID = 18
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürünler",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Products/Add",
                            ParentID = 19
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürünler",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Products/Update",
                            ParentID = 19
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürünler",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Products/Delete",
                            ParentID = 19
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürünler",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Products/Detail",
                            ParentID = 19
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductTypes/List",
                            ParentID = 18
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductTypes/Add",
                            ParentID = 24
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductTypes/Update",
                            ParentID = 24
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductTypes/Delete",
                            ParentID = 24
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductTypes/Detail",
                            ParentID = 24
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Genel Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "#"
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Hakkımızda",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Contacts/List",
                            ParentID = 29
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Hakkımızda",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Contacts/Add",
                            ParentID = 30
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Hakkımızda",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Contacts/Update",
                            ParentID = 30
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Hakkımızda",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Contacts/Delete",
                            ParentID = 30
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Hakkımızda",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Contacts/Detail",
                            ParentID = 30
                        });
                });

            modelBuilder.Entity("Entities.Concrete.PagePermisson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppOperationClaimId")
                        .HasColumnType("int");

                    b.Property<int?>("AppUserTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OperationClaimID")
                        .HasColumnType("int")
                        .HasColumnName("OperationClaimID");

                    b.Property<int>("PageID")
                        .HasColumnType("int")
                        .HasColumnName("PageID");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.HasKey("Id");

                    b.HasIndex("AppOperationClaimId");

                    b.HasIndex("AppUserTypeId");

                    b.HasIndex("PageID");

                    b.ToTable("PagePermissons", "dbo");
                });

            modelBuilder.Entity("Entities.Concrete.PageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PageTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PageTypeName");

                    b.HasKey("Id");

                    b.ToTable("PageTypes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PageTypeName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PageTypeName = "Web"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUser", b =>
                {
                    b.HasOne("Entities.Concrete.AppUserType", "AppUserType")
                        .WithMany("AppUsers")
                        .HasForeignKey("AppUserTypeId");

                    b.Navigation("AppUserType");
                });

            modelBuilder.Entity("Entities.Concrete.AppUserTypeAppOperationClaim", b =>
                {
                    b.HasOne("Entities.Concrete.AppOperationClaim", "AppOperationClaim")
                        .WithMany("AppUserTypeAppOperationClaims")
                        .HasForeignKey("AppOperationClaimId");

                    b.HasOne("Entities.Concrete.AppUserType", "AppUserType")
                        .WithMany()
                        .HasForeignKey("AppUserTypeId");

                    b.Navigation("AppOperationClaim");

                    b.Navigation("AppUserType");
                });

            modelBuilder.Entity("Entities.Concrete.Page", b =>
                {
                    b.HasOne("Entities.Concrete.PageType", "PageType")
                        .WithMany("Pages")
                        .HasForeignKey("PageTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageType");
                });

            modelBuilder.Entity("Entities.Concrete.PagePermisson", b =>
                {
                    b.HasOne("Entities.Concrete.AppOperationClaim", "AppOperationClaim")
                        .WithMany("PagePermissons")
                        .HasForeignKey("AppOperationClaimId");

                    b.HasOne("Entities.Concrete.AppUserType", "AppUserType")
                        .WithMany("PagePermissons")
                        .HasForeignKey("AppUserTypeId");

                    b.HasOne("Entities.Concrete.Page", "Page")
                        .WithMany("PagePermissons")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppOperationClaim");

                    b.Navigation("AppUserType");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Entities.Concrete.AppOperationClaim", b =>
                {
                    b.Navigation("AppUserTypeAppOperationClaims");

                    b.Navigation("PagePermissons");
                });

            modelBuilder.Entity("Entities.Concrete.AppUserType", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("PagePermissons");
                });

            modelBuilder.Entity("Entities.Concrete.Page", b =>
                {
                    b.Navigation("PagePermissons");
                });

            modelBuilder.Entity("Entities.Concrete.PageType", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
